test_absolute (__main__.TestExercice) ... ok
test_factorial (__main__.TestExercice) ... ERROR
test_prefixes (__main__.TestExercice) ... ERROR
test_summation (__main__.TestExercice) ... ERROR
test_verify_ages (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 56, in test_factorial
    output = [exercice.factorial(v) for v in values]
  File "test_exercice.py", line 56, in <listcomp>
    output = [exercice.factorial(v) for v in values]
AttributeError: module 'exercice' has no attribute 'factorial'

======================================================================
ERROR: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 26, in test_prefixes
    output = exercice.use_prefixes()
AttributeError: module 'exercice' has no attribute 'use_prefixes'

======================================================================
ERROR: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 45, in test_summation
    output = exercice.prime_integer_summation()
AttributeError: module 'exercice' has no attribute 'prime_integer_summation'

======================================================================
ERROR: test_verify_ages (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 72, in test_verify_ages
    output = exercice.verify_ages(groups)
AttributeError: module 'exercice' has no attribute 'verify_ages'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=4)
